# Generated by Django 4.1.2 on 2022-11-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_admin_chat_title_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
